[package]
name = "spice-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
dyn-clone = "1.0.17"
nalgebra = "0.32.5"
thiserror = "1.0.61"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "dc_run"
harness = false